apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "nginx-redirect.fullname" . }}
  labels:
    {{- include "nginx-redirect.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        server_name  localhost default_server;
        location / {
          default_type text/html;
          return 404 "404 - not found";
        }
        location /healthz {
          default_type text/html;
          return 200 "ok";
        }
    }
{{- range .Values.redirects }}
  {{ .host }}.conf: |
    server {
      listen       80;
      server_name  {{ .host }};

      {{- range .paths }}
      location {{ .path }} {
        return {{ default 302 .type }} {{ .dest }};
      }
      {{- end }}
    }
{{- end }}