{{ range .Values.serviceAccounts -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "Missing value .Values.serviceAccounts[].name" .name | quote }}
  
  {{- with (merge (default .annotations (dict)) $.Values.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with (merge (default .labels (dict)) $.Values.labels) }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}


  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{ end -}}
