name: Release Charts
on:
  push:
    branches:
      - master

jobs:
  release:
    if: github.repository == 'fossas/charts-util'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@b5b231a831f96336bbfeccc1329990f0005c5bb1
        with:
          version: v3.10.0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@98bccfd32b0f76149d188912ac8e45ddd3f8695f
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
